import "./globals.css";

import SideBar from "./(components)/SideBar";
import RightSection from "./(components)/RightSection";
import AnalyticsPage from "./AnalyticsPage/page";

export const metadata = {
  title: "Dashboard | Appian Graphics",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons+Sharp"
          rel="stylesheet"
        />
      </head>
      <body>
        <div className="container">
          <SideBar />

          <main>{children}</main>

          <RightSection />
        </div>
      </body>
    </html>
  );
}
